language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
script:
- touch foo
deploy:
  provider: pypi
  user: martin.majlis
  password:
    secure: jYDrU/cy2sc0QLkQ6RUxqJO+iJoGojYeDmnpbh1kZSlgxclcJxXcOWK8ron2HJLBhXUsOaJ98pymALapZlgChFfIl2sZTzhmmseKDcljmCyWlzBC5jq6DtAUSWKc5c5R9xgZgs856DZlGRw3YnYBX3XMl9dcRJJYM0Ze/z//0AGWQzpMJbvDPj4vJSbXBqt+siHI/AIWxV0z5KYPh1A7Edl1/aVpKl2WHrdeWlGDwqPb504UXVKbp3z9ANrjWzv8ReBt5eRQ/RO8uiovhQMAgh2P5DNWkdCVbXISjx+UBWhY47vYRZZbXfdLArBQd1YFD89q36agpFOBV5NZuu9TYWLDXI4c+EwZeQnTrGhsPA88ojJb4Ca9VJEOOWQi5hS43kHvaPXn7Q/sK5GC5bsQwfCgqqmXRJVIh4lreQwKf5hoC1/DnCaU25xkodJJFYj8pDgWEe40nwnF1qV4w2UyhLMH1HbMeu8AJAEFIGljsnKFd+7meJUf97O+9r0zTzj1HgXrTWW98Rk2KHtZX9WTqYugEy6Rm1qQU35e92lA3La09qpLCRPStAzSz2mlVGqV0wxWob/tO1vDAcWHERBgOlmjVbHEkvHQn0wT8o8iACdFiQTPPQOdKKmVrP2gq0h6+Sy1v4bU7gosxPc+dmwuc9YnFvOBnM960nU+ZiMIcE8=
  on:
    tags: true
after_sucess:
- CODECLIMATE_REPO_TOKEN=f71b8777af3523a62c1b487e7d590e1894353daa codeclimate-test-reporter
